from app.mcp.server import mcp_server


@mcp_server.resource("cmms://graph/schema")
async def graph_schema() -> str:
    """Description of the Neo4j graph schema."""
    return (
        "CMMS Knowledge Graph Schema\n"
        "\n"
        "Node Labels and Properties:\n"
        "- Asset: pg_id, name, description, asset_type, "
        "status, location, created_at, updated_at\n"
        "- Sensor: pg_id, name, sensor_type, unit, "
        "status, created_at, updated_at\n"
        "- SensorSummary: sensor_pg_id, window "
        "(1h|6h|24h|7d|30d), window_start, window_end,\n"
        "    avg_value, min_value, max_value, stddev, "
        "sample_count, anomaly_flag\n"
        "- Fault: pg_id, code, name, description, "
        "severity (low|medium|high|critical),\n"
        "    status (open|investigating|resolved|closed), "
        "detected_at, resolved_at, created_at, updated_at\n"
        "- MaintenanceSchedule: pg_id, title, description, "
        "maintenance_type (preventive|corrective|predictive),\n"
        "    status (scheduled|in_progress|completed|cancelled|"
        "overdue), priority (low|medium|high|critical),\n"
        "    scheduled_date, completed_date, assigned_to, "
        "recurrence (none|daily|weekly|monthly|quarterly|yearly),\n"
        "    estimated_duration_hours, notes, "
        "created_at, updated_at\n"
        "\n"
        "Relationships:\n"
        "- (Asset)-[:HAS_PARENT]->(Asset) "
        "— Child → Parent hierarchy\n"
        "- (Asset)-[:HAS_SENSOR]->(Sensor) "
        "— Asset's monitoring sensors\n"
        "- (Sensor)-[:HAS_SUMMARY]->(SensorSummary) "
        "— Aggregated reading summaries\n"
        "- (Asset)-[:HAS_FAULT]->(Fault) "
        "— Faults detected on asset\n"
        "- (Fault)-[:CAUSES]->(Fault) "
        "— Cause-effect fault propagation\n"
        "- (Asset)-[:HAS_MAINTENANCE]->(MaintenanceSchedule) "
        "— Maintenance for asset\n"
        "- (MaintenanceSchedule)-[:ADDRESSES_FAULT]->(Fault) "
        "— Optional fault linkage"
    )
