from app.mcp.server import mcp_server


@mcp_server.resource("cmms://graph/schema")
async def graph_schema() -> str:
    """Description of the Neo4j graph schema."""
    return (
        "CMMS Knowledge Graph Schema\n"
        "\n"
        "Node Labels and Properties:\n"
        "- Asset: pg_id, name, description, asset_type, "
        "status, location, created_at, updated_at\n"
        "- Sensor: pg_id, name, sensor_type, unit, "
        "status, created_at, updated_at\n"
        "- Fault: pg_id, code, name, description, "
        "severity (low|medium|high|critical),\n"
        "    status (open|investigating|resolved|closed), "
        "detected_at, resolved_at, created_at, updated_at\n"
        "- MaintenanceSchedule: pg_id, title, description, "
        "maintenance_type (preventive|corrective|predictive),\n"
        "    status (scheduled|in_progress|completed|cancelled|"
        "overdue), priority (low|medium|high|critical),\n"
        "    scheduled_date, completed_date, assigned_to, "
        "recurrence (none|daily|weekly|monthly|quarterly|yearly),\n"
        "    estimated_duration_hours, notes, "
        "created_at, updated_at\n"
        "\n"
        "Relationships:\n"
        "- (Asset)-[:HAS_PARENT]->(Asset) "
        "— Child → Parent hierarchy\n"
        "- (Asset)-[:HAS_SENSOR]->(Sensor) "
        "— Asset's monitoring sensors\n"
        "- (Asset)-[:HAS_FAULT]->(Fault) "
        "— Faults detected on asset\n"
        "- (Fault)-[:CAUSES]->(Fault) "
        "— Cause-effect fault propagation\n"
        "- (Asset)-[:HAS_MAINTENANCE]->(MaintenanceSchedule) "
        "— Maintenance for asset\n"
        "- (MaintenanceSchedule)-[:ADDRESSES_FAULT]->(Fault) "
        "— Optional fault linkage\n"
        "\n"
        "New Node Labels:\n"
        "- Worker: pg_id, name, employee_id, email, phone, status, "
        "created_at, updated_at\n"
        "- Role: pg_id, name, description, created_at, updated_at\n"
        "- Competence: pg_id, name, description, category, "
        "created_at, updated_at\n"
        "- Level: pg_id, name, rank, description, created_at, updated_at\n"
        "- Task: pg_id, name, description, task_type, status, "
        "estimated_duration_hours, doc_link, created_at, updated_at\n"
        "- Action: pg_id, name, description, action_type, "
        "sequence_order, created_at, updated_at\n"
        "- Cause: pg_id, name, description, category, severity, "
        "created_at, updated_at\n"
        "- Material: pg_id, name, part_number, description, "
        "quantity_in_stock, unit, created_at, updated_at\n"
        "- Shift: pg_id, name, start_time, end_time, description, "
        "created_at, updated_at\n"
        "- DownEvent: pg_id, asset_id, started_at, ended_at, "
        "downtime_minutes, description, severity, status, "
        "created_at, updated_at\n"
        "- Order: pg_id, order_number, title, description, "
        "order_type, status, priority, requested_date, "
        "created_at, updated_at\n"
        "- Location: pg_id, name, description, location_type, "
        "parent_id, created_at, updated_at\n"
        "- System: pg_id, name, description, created_at, updated_at\n"
        "- Aggregate: pg_id, name, description, created_at, updated_at\n"
        "\n"
        "New Relationships:\n"
        "- (Asset)-[:assigned_to]->(Worker) "
        "— Worker assigned to equipment\n"
        "- (Worker)-[:has]->(Competence) "
        "— Worker possesses a competence\n"
        "- (Worker)-[:works_in]->(Shift) "
        "— Worker works in a shift\n"
        "- (Competence)-[:typeOf]->(Level) "
        "— Competence has proficiency level\n"
        "- (Task)-[:requires]->(Competence) "
        "— Task requires a competence\n"
        "- (Cause)-[:requires]->(Role) "
        "— Resolving cause requires a role\n"
        "- (Action)-[:requires]->(Competence) "
        "— Action requires a competence\n"
        "- (Asset)-[:consists_of]->(System) "
        "— Equipment consists of systems\n"
        "- (System)-[:part_of]->(Aggregate) "
        "— System is part of an aggregate\n"
        "- (Role)-[:enables]->(Task) "
        "— Role enables performing a task\n"
        "- (Asset)-[:is_at]->(Location) "
        "— Equipment is at a location\n"
        "- (Order)-[:booked_on]->(Asset) "
        "— Order is booked on equipment\n"
        "- (Material)-[:planned_in]->(Task) "
        "— Material is planned for a task\n"
        "- (DownEvent)-[:has]->(Cause) "
        "— Down event has a cause"
    )
